"""Changed Relation type

Revision ID: c3ab708df136
Revises: f29c30a895d5
Create Date: 2023-03-20 20:40:13.351254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ab708df136'
down_revision = 'f29c30a895d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_country_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('to_country_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('create-foreign-key-from-country', 'country', ['to_country_id'], ['id'])
        batch_op.create_foreign_key('create-foreign-key-to-country', 'country', ['from_country_id'], ['id'])
        batch_op.drop_column('from_country')
        batch_op.drop_column('to_country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_country', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('from_country', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'country', ['to_country'], ['name'])
        batch_op.create_foreign_key(None, 'country', ['from_country'], ['name'])
        batch_op.create_foreign_key(None, 'country', ['to_country'], ['id'])
        batch_op.create_foreign_key(None, 'country', ['from_country'], ['id'])
        batch_op.drop_column('to_country_id')
        batch_op.drop_column('from_country_id')

    # ### end Alembic commands ###
