"""Initial migration.

Revision ID: f29c30a895d5
Revises: 
Create Date: 2023-03-20 20:27:31.689233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29c30a895d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculation', schema=None) as batch_op:
        batch_op.alter_column('from_country',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('to_country',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_foreign_key('create-foreign-key-from-country', 'country', ['to_country'], ['name'])
        batch_op.create_foreign_key('create-foreign-key-to-country', 'country', ['from_country'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'country', ['to_country'], ['id'])
        batch_op.create_foreign_key(None, 'country', ['from_country'], ['id'])
        batch_op.alter_column('to_country',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('from_country',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
